# Basic
title: Bynnebw
subtitle: This is the personal blog belonging to Bryan Zhang
welcome_message: <a href="https://github.com/bynnebw/dataStructure" target="_blank">This is the mainly project recently</a>
description: The blog is to record the ideas and the knowledge or the skills that I've been learnt from the whole process of the study.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: keepo
    github: bynnebw
    twitter: onevcat
    gplus: 107108267983477358170
    mail: 1365584663@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
